### ISSUE TITLE
How do i use it?

### ISSUE THREAD

**Issue by Veis2015** [lucidrains/DALLE2-pytorch#1]
Title explains it all

**Comment by lucidrains** [comment]
hello! the plan is to have it be a single command line tool like https://github.com/lucidrains/deep-daze and https://github.com/lucidrains/big-sleep

but it needs to be built and then trained

**Comment by franva** [comment]
> hello! the plan is to have it be a single command line tool like https://github.com/lucidrains/deep-daze and https://github.com/lucidrains/big-sleep
> 
> but it needs to be built and then trained

How many GPUs does the training need? Is it possible to train it on a personal computer within reasonable time e.g. couple of hours?

**Comment by lucidrains** [comment]
@franva definitely not, but there are plenty of people with compute floating about at https://discord.com/invite/UxX8dv5KMh you should go mingle with the open source people there, if you are willing to contribute
