### ISSUE TITLE
making decoder dataloaders something wrong

### ISSUE THREAD

**Issue by LearningJack** [lucidrains/DALLE2-pytorch#110]
![issue](https://user-images.githubusercontent.com/38984606/169820565-180a04d3-4f88-4ff6-83df-07d03838a208.jpg)
Could you help me? I had run the **clip-retrieval** and then generate the embedding.npy.But when I run the **reorder-embeddings**, it occured **invalid literal for int() with base 10: 'img_test/COCO_train2014_000000581909'**. How can I solve this problem?

**Comment by rom1504** [comment]
You need to download using webdataset format when using img2dataset

**Comment by LearningJack** [comment]
But when I have my own dataset, how can I resolve this issue?
