### ISSUE TITLE
Model dalle2.pt is missing

### ISSUE THREAD

**Issue by marcellopajntar** [lucidrains/DALLE2-pytorch#119]
Hey @lucidrains, how are you?
I'm trying to run your repo locally just for test and after installed pip package dalle2-pytorch i tried to run a simple prompt but it does't work due to dalle2.pt file that missing, maybe i have to train it first? if yes how? Thanks :)

P.s. Can i run project without cuda?

**Comment by lucidrains** [comment]
@marcellopajntar yea, it still needs to be trained - recommend you join the Laion community and chip in with whatever talent you have
