### ISSUE TITLE
Classifier-Free Guidance for Image Embed Conditioning

### ISSUE THREAD

**Issue by xvjiarui** [lucidrains/DALLE2-pytorch#144]
Hi @lucidrains 

In your implementation [here](https://github.com/lucidrains/DALLE2-pytorch/blob/0f319803620c204e61c6b580f65e8689ea71d6e8/dalle2_pytorch/dalle2_pytorch.py#L1566), the image embedding is added to the time embedding as Sec. 2.1 in paper 
> projecting and adding CLIP embeddings to the existing timestep embedding

However, I am wondering whether the current implementation is still classifier-free guidance. Currently, we don't drop `image_hiddens` randomly, so it is always conditioned on image embedding, I think?

Please feel free to point me out if I am wrong.

**Comment by lucidrains** [comment]
@xvjiarui oh gosh, thank you for catching this bug! :man_facepalming: :pray:  i've fixed it at https://github.com/lucidrains/DALLE2-pytorch/commit/5d958713c0753922b64086b2310324c1f3be64e5 hope this is the last one..

**Comment by xvjiarui** [comment]
Wow, that's fast! 
Thank you!
