### ISSUE TITLE
Generating Multiple Outputs

### ISSUE THREAD

**Issue by egeozsoy** [lucidrains/DALLE2-pytorch#146]
Is there a suggested way of generating multiple image outputs given a text input, like the 9-10 outputs dalle2 produces?

**Comment by lucidrains** [comment]
@egeozsoy you could do it yourself easily by `images = dalle2(['your prompt'] * num_outputs)`

**Comment by lucidrains** [comment]
@egeozsoy i'm guessing you have trained something decent?

**Comment by egeozsoy** [comment]
At least something that gives me some results haha. That sounds like a very easy solution, will try it out

**Comment by lucidrains** [comment]
but knowing researchers, you are probably scrambling for a paper to be written / avoid being scooped, so hearing silence is good enough signal for me haha

**Comment by egeozsoy** [comment]
I am working on a very specific topic, surgical video generation. So the results are maybe not very interesting. But once I have something that works (right now, I think I am getting overfitting problems a lot), I will share :)

**Comment by lucidrains** [comment]
@egeozsoy nice! surgical video is very interesting! laparoscopy?

**Comment by lucidrains** [comment]
ok, you go do your thing

**Comment by lucidrains** [comment]
@egeozsoy very cool! and yeah 7k images isn't a lot of data

but the new Tero Karras paper https://arxiv.org/abs/2206.00364 brings in some augmentation tricks that may benefit the small data setting. i'll eventually build that into this repository and some other DDPM repositories once i see some positive results

**Comment by egeozsoy** [comment]
Thanks for the suggestions, It is really about testing the limited data regime for dalle2 for now. Interested in seeing how it performs with 1000x less data :)
