### ISSUE TITLE
EMA Averages The Steps?

### ISSUE THREAD

**Issue by nousr** [lucidrains/DALLE2-pytorch#149]
https://github.com/lucidrains/DALLE2-pytorch/blob/6651eafa937000ec72ef3b3892e22a8dc2997316/dalle2_pytorch/trainer.py#L275-L278

...this is gonna average the `self.steps` attribute too, yeah? we should probably not do that...? unless someone has a convincing argument otherwise lol

**Comment by lucidrains** [comment]
@nousr hey! no it should be fine because the `step` is on the trainer module, and the EMA only wraps the diffusion prior and the decoder unets
