### ISSUE TITLE
Moved toy task to the end

### ISSUE THREAD

**Issue by INF800** [lucidrains/DALLE2-pytorch#15]
Hi. Few hours back, you had toy task as your (almost) next item and now it is moved to the end in your check-list.

Are you facing any major challenges for training on the toy task? If not, please let me know -- I have beefy GPUs available with me for training on toy task -- will do it parallely with you!

---
Before:

![IMG_20220418_213547](https://user-images.githubusercontent.com/45640029/163883659-6f44b190-9d53-43df-bae3-9741cdf2fb93.jpg)

Now:

![IMG_20220419_031840](https://user-images.githubusercontent.com/45640029/163883768-20202877-b9cc-4121-a848-5770fd5e8506.jpg)

**Comment by lucidrains** [comment]
relax, i'll get there :)
