### ISSUE TITLE
Timestep Respacing

### ISSUE THREAD

**Issue by nousr** [lucidrains/DALLE2-pytorch#157]
(perhaps unsurprisingly) We are discovering that 1000 steps for the prior and decoder takes quite a while, especially on consumer and colab GPUs.

How hard would it be to add time step re-spacing, and other sampling methods (like plms)?

**Comment by harubaru** [comment]
Would love to see this -- currently it takes forever to do inference with many images, for reference only 250 sampling steps are used for the decoder according to the DALL-E 2 paper 😅

![image](https://user-images.githubusercontent.com/26317155/177008386-9781b673-8271-490b-a184-78e3648c2378.png)

**Comment by lucidrains** [comment]
should be done, i think

it is working fine for my oxford flowers dataset over at https://github.com/lucidrains/denoising-diffusion-pytorch

**Comment by nousr** [comment]
> should be done, i think
> 
> it is working fine for my oxford flowers dataset over at https://github.com/lucidrains/denoising-diffusion-pytorch

awesome, thanks! will try it out in a bit...

we literally were talking last night about how this would be really nice to have now that we're benchmarking :D

**Comment by lucidrains** [comment]
@nousr ok! feel free to reopen it if some bug pops up

**Comment by 1073521013** [comment]
Hello, I am currently research some similar work such as ddim, DPM-Solver, FastDPM, etc. At present, I have verified the ddim reproduce by you and found that the effect after add time step re-spacing is not ideal, and it is still under research, thank you
sample with 250,17
![1 (34)](https://user-images.githubusercontent.com/26042094/180213707-8a30164e-db67-4ac0-9abd-5be0e931c9ef.jpg)
sample with 1000,1000
![1 (37)](https://user-images.githubusercontent.com/26042094/180213875-4d397021-86ec-4855-a5fc-d32ca1645ad0.jpg)

**Comment by 1073521013** [comment]
Through experimental verification, it is found that when the unet classifier-free guidance weight is greater than or equal to 5, the ddim strategy will not work after dynamic threshold adjustment, it will be better to remove the dynamic threshold adjustment.
Maybe using high guide weights will push the predictions out of these bounds and then there may be some kind of conflict with ddim sampling for threshold clipping,but still haven't fully understood the reason

**Comment by YUHANG-Ma** [comment]
> Through experimental verification, it is found that when the unet classifier-free guidance weight is greater than or equal to 5, the ddim strategy will not work after dynamic threshold adjustment, it will be better to remove the dynamic threshold adjustment. Maybe using high guide weights will push the predictions out of these bounds and then there may be some kind of conflict with ddim sampling for threshold clipping,but still haven't fully understood the reason

Hi, I also met this problem. What should I do after removing the dynamic threshold adjustment?

**Comment by heurainbow** [comment]
> should be done, i think
> 
> it is working fine for my oxford flowers dataset over at https://github.com/lucidrains/denoising-diffusion-pytorch

I wonder if this is a plugin that works for model already trained with 1000 steps?
Can this solve problems in #177?
