### ISSUE TITLE
p2_loss_weight causing problems for prior checkpoints

### ISSUE THREAD

**Issue by nousr** [lucidrains/DALLE2-pytorch#158]
The current prior checkpoints were trained before p2_loss_weight was added. As a result, it is not possible to load these checkpoints in the latest version. 

According to @Veldrovive settings `strict=False`does allow you to load the checkpoint--but results in garbage predictions.

Is there a way we can patch this to allow the old checkpoints to work with the latest repo?

**Comment by lucidrains** [comment]
@nousr so i think the version on which the model was trained on should be saved in the .pt file, and you can just make sure to `pip install dalle2-pytorch=={version}` before loading it

actually made sure to build this early on because i had trouble with this in other repositories

**Comment by Veldrovive** [comment]
The problem is that the pretrained decoder only works on `>0.10.1` and the pretrained prior only works on `0.7.0`. We are just looking for a workaround so that the prior and decoder can be loaded at the same time. Some value to put in for `p2_loss_weight` in the state dict or something.

**Comment by lucidrains** [comment]
i think it is probably best to just load with `strict = False` and finetune for an epoch or two

**Comment by Veldrovive** [comment]
Ah, that's smart. @nousr would you be able to do that?
