### ISSUE TITLE
Any colab notebooks with pretrained models available?

### ISSUE THREAD

**Issue by prp-e** [lucidrains/DALLE2-pytorch#168]
Greetings. 
I found this repository and since I'm doing some AI Art stuff going on, I am looking for colab notebooks and pretrained models for this repo. I'd be thankful if there's any and you give a link to me.

**Comment by XieBaoshi** [comment]
Try this one https://colab.research.google.com/drive/1RVvKbp5dWn46ME5dYv_OxycRh4QKWw7x (by Aidan and Nousr). It's a very early version that only has prior and decoder.

**Comment by rom1504** [comment]
You can find some more in https://github.com/LAION-AI/dalle2-laion

**Comment by prp-e** [comment]
i get this when I work with the notebook @XieBaoshi linked:
```
---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

[<ipython-input-9-cf76c2be222f>](https://localhost:8080/#) in <module>()
     84     img.save(f"./reranked_output/example_{index}.png")
     85 
---> 86 rerank_test(5, 50)

1 frames

[<ipython-input-6-eb7fb2d7bc08>](https://localhost:8080/#) in format_image_grid(img_array)
    151   rows = max_decoder_index + 1
    152 
--> 153   w, h = example_image.size
    154   grid = Image.new('RGB', size=(cols*w, rows*h))
    155   grid_w, grid_h = grid.size

TypeError: cannot unpack non-iterable builtin_function_or_method object
```
