### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by AhmedEwis** [lucidrains/DALLE2-pytorch#170]
While implementing the code, 
I found that this repo is half public and half private.
How can I have the full code?
 it is restricted by owner @lucidrains 
it should has access rights on it.

Thanks!

**Comment by lucidrains** [comment]
@AhmedEwis you have full access to the code, not to mention the license is MIT, so free to copy / paste, redistribute etc

if you mean being able to change the code, you will need to fork the repository and then submit a pull request

**Comment by AhmedEwis** [comment]
I got it thanks @lucidrains!
