### ISSUE TITLE
Potential misleading decoder option

### ISSUE THREAD

**Issue by Veldrovive** [lucidrains/DALLE2-pytorch#174]
The decoder constructor takes the parameter `condition_on_text_encodings`, but I do not think setting this to true makes any difference besides erroring when a text encoding is not supplied. The real option to use text conditioning is on the unet and is named `cond_on_text_encodings`, but setting `condition_on_text_encodings=True` does not have any effect here. 

https://github.com/lucidrains/DALLE2-pytorch/blob/f5760bdb92fb8fe9f53aca4a87b3e4b9ef8cdbaa/dalle2_pytorch/dalle2_pytorch.py#L1853-L1859

It would be a quick fix to either enforce the value of `condition_on_text_encodings` on every unet or just remove this parameter in favor of only having the configuration on the unets.

**Comment by lucidrains** [comment]
@Veldrovive thanks Aidan! decided to go with just enforcing the first unet to be always text conditionable (if not unconditional) https://github.com/lucidrains/DALLE2-pytorch/commit/2e85e736f30b9c6d0c9802c10902b810d200741b

**Comment by lucidrains** [comment]
actually, shouldn't enforce text encodings are present, so it goes back to the way it was (but without the redundant parameter)
