### ISSUE TITLE
ModuleNotFoundError:

### ISSUE THREAD

**Issue by Eliza-wxq** [lucidrains/DALLE2-pytorch#176]
ModuleNotFoundError: No module named 'dalle2_pytorch.vqgan_vae'; 'dalle2_pytorch' is not a package

**Comment by lucidrains** [comment]
@Eliza-wxq did you run `pip install dalle2-pytorch` first?

**Comment by Eliza-wxq** [comment]
yes,I did

**Comment by rom1504** [comment]
There's no vqgan vae in dalle2, you're running the wrong script
