### ISSUE TITLE
sampling steps

### ISSUE THREAD

**Issue by BinglengTang** [lucidrains/DALLE2-pytorch#177]
What is "sampling steps= 250, 27, 15" used for ? I have no idea that where is these parameters used in the codes. I have tried that training with diffusion steps = 1000 and evaluated with diffusion steps = 250. The generated images are all noised images.

**Comment by nousr** [comment]
where are you seeing this?

**Comment by BinglengTang** [comment]
In the table.3 described in Section C. And also explained in glide paper

**Comment by nousr** [comment]
i believe this references the time-step re-spacing. although you train 1,000 diffusion steps--it is possible to sample with less at inference time. So they are saying that they sample 250 steps for the decoder, 27 for the first upscaler, and 15 for the last

**Comment by BinglengTang** [comment]
I  have trained trying with 1000 diffusion steps and test with 250 steps, the generated images are also noised images. You can do your onw experiments. I think this is not the right answer.

**Comment by nousr** [comment]
the functionality to sample with less steps at inference time is not implemented in this codebase yet. 

in other words, you will need to sample with all 1,000 steps at inference time to properly evaluate your model. 

>

**Comment by BinglengTang** [comment]
I do not think that sampling with 250 steps can generate the right images. I believe that training the upsampler with 27 and 15 steps may be the right answer since the task is far more easier than the base decoder.

**Comment by lucidrains** [comment]
> the functionality to sample with less steps at inference time is not implemented in this codebase yet. in other words, you will need to sample with all 1,000 steps at inference time to properly evaluate your model.
> […](#)
> On Jun 28, 2022, at 8:11 PM, Bingleng Tang ***@***.***> wrote: ﻿ I have trained trying with 1000 diffusion steps and test with 250 steps, the generated images are also noised images. You can do your onw experiments. I think this is not the right answer. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

@BinglengTang  this is the right answer

**Comment by lucidrains** [comment]
@BinglengTang don't worry, it will be built soon
