### ISSUE TITLE
train_decoder webdataset.filters.pipelinefilter error

### ISSUE THREAD

**Issue by MalindaH** [lucidrains/DALLE2-pytorch#178]
Hello! I got this error when running `train_decoder.py`:

My prompt: `python3 /home/malinda/DALLE2-pytorch/train_decoder.py --config_file=/home/malinda/DALLE2-pytorch/configs/train_decoder_config.example.json`
```
Traceback (most recent call last):
  File "/home/malinda/DALLE2-pytorch/train_decoder.py", line 4, in <module>
    from dalle2_pytorch.dataloaders import create_image_embedding_dataloader
  File "/home/malinda/DALLE2-pytorch/dalle2_pytorch/dataloaders/__init__.py", line 1, in <module>
    from dalle2_pytorch.dataloaders.decoder_loader import ImageEmbeddingDataset, create_image_embedding_dataloader
  File "/home/malinda/DALLE2-pytorch/dalle2_pytorch/dataloaders/decoder_loader.py", line 66, in <module>
    insert_embedding = wds.filters.pipelinefilter(embedding_inserter)
AttributeError: module 'webdataset.filters' has no attribute 'pipelinefilter'
```
I looked up `webdataset.filters` documentation [here](https://webdataset.github.io/webdataset/api/webdataset/filters.html) and I couldn't find `pipelinefilter`.

How can I resolve this error? Thank you!

**Comment by YUHANG-Ma** [comment]
You need to install webdataset==0.2.5 instead of 0.1.x
