### ISSUE TITLE
AssertionError: You must supply some method of obtaining a device.

### ISSUE THREAD

**Issue by Xtreamzz** [lucidrains/DALLE2-pytorch#187]
Hi! i got this error when running [Diffusion Prior Training]:

AssertionError                            Traceback (most recent call last)
[<ipython-input-6-3754abe97b33>](https://localhost:8080/#) in <module>()
     43     ema_beta = 0.99,
     44     ema_update_after_step = 1000,
---> 45     ema_update_every = 10,
     46 )
     47 

[/usr/local/lib/python3.7/dist-packages/dalle2_pytorch/trainer.py](https://localhost:8080/#) in __init__(self, diffusion_prior, use_ema, lr, wd, eps, max_grad_norm, amp, group_wd_params, device, accelerator, verbose, **kwargs)
    174         assert isinstance(diffusion_prior, DiffusionPrior)
    175         assert not exists(accelerator) or isinstance(accelerator, Accelerator)
--> 176         assert exists(accelerator) or exists(device), "You must supply some method of obtaining a device."
    177         ema_kwargs, kwargs = groupby_prefix_and_trim('ema_', kwargs)
    178 

AssertionError: You must supply some method of obtaining a device.

what should i do?

**Comment by nousr** [comment]
you'll need to pass in a device or utilize huggingface accelerate to train the model

if you can give a bit more context for how you're running the script and any modifications you might have made I can help you debug further

the relevant portions of the script should be here and here
https://github.com/lucidrains/DALLE2-pytorch/blob/1bd8a7835ab66f266daf11cff2aa56ed6a46a001/train_diffusion_prior.py#L348-L357

https://github.com/lucidrains/DALLE2-pytorch/blob/1bd8a7835ab66f266daf11cff2aa56ed6a46a001/train_diffusion_prior.py#L41-L59

**Comment by lucidrains** [comment]
@nousr @Xtreamzz decided to just have it fallback to the device that the diffusion prior model parameters are on https://github.com/lucidrains/DALLE2-pytorch/commit/e928ae5c346846e87257ff6db5a08cc8d7c58980 (with a warning message)

**Comment by lucidrains** [comment]
@nousr haha yea, they probably are doing their own thing

people often remix code for their own tangential research

**Comment by Xtreamzz** [comment]
i ran everything sequentially according to the one in the readme without anything changed, is there a step i should do that is not in the readme ? and also can I ask for a google colab link that can be run correctly for my college assignment? i was assigned to understand how dalle 2 works

**Comment by lucidrains** [comment]
@Xtreamzz yea that's my fault, the readme should run

however, it is recommended to use the `train_diffusion_prior.py` script that is in the repository root, @nousr Zion has written up a section for it recently! https://github.com/lucidrains/DALLE2-pytorch/blob/main/prior.md
