### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'condition_on_text_encodings'

### ISSUE THREAD

**Issue by FadhilRa** [lucidrains/DALLE2-pytorch#189]
Hello! can anyone help me
When I try to run the OpenAI Clip section in the readme, an error appears like this

TypeError                                 Traceback (most recent call last)
[<ipython-input-5-6e64c5f16130>](https://localhost:8080/#) in <module>()
     57     image_cond_drop_prob = 0.1,
     58     text_cond_drop_prob = 0.5,
---> 59     condition_on_text_encodings = False  # set this to True if you wish to condition on text during training and sampling
     60 ).cuda()
     61 

TypeError: __init__() got an unexpected keyword argument 'condition_on_text_encodings'

I tried to run it without anything I changed

**Comment by lucidrains** [comment]
@FadhilRa Oh oops, we changed that setting to be on the `Unet` class

Readme should be updated now and work without errors!
