### ISSUE TITLE
Decoder Training - Warn when image is smaller than clip image size

### ISSUE THREAD

**Issue by Veldrovive** [lucidrains/DALLE2-pytorch#190]
When using on the fly image embedding generation, it hurts the quality of the embedding if the preprocessing has cropped the image to smaller than the clip input size. As an improvement to the decoder training script, it should warn the user if the image has been cropped too much.

Extra requirements:
* Warn early. It can take a while for setup to happen and we want to be able to see the warning before the first forward pass.

I can handle this when I have time, but it could also be worked on by anyone who has a working knowledge of python.

**Comment by lucidrains** [comment]
@Veldrovive went with the most straightforward way to address this https://github.com/lucidrains/DALLE2-pytorch/commit/30706102312a22d2d327a98c2cbd06cd62d99473

**Comment by Veldrovive** [comment]
Yep, that'll do it
