### ISSUE TITLE
 Warning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP wa s constructed.  This is not an error, but may impair performance.

### ISSUE THREAD

**Issue by YUHANG-Ma** [lucidrains/DALLE2-pytorch#196]
Hi all, I still didn't figure out why this warning could appears. 
![image](https://user-images.githubusercontent.com/72591225/178094200-1f941b45-5ce4-4890-b70e-2ea26ea78ff1.png)

I found that when I update my dalle2_pytorch.py to https://github.com/lucidrains/DALLE2-pytorch/commit/3d23ba4aa5fec8177e1637847999ff2c5786f41c this version, the warning appears. But it didn't happen with previour version. I set my configs as :
    "decoder": {
        "unets": [
            {
                "dim": 128,
                "image_embed_dim": 768,
                "cond_dim": 64,
                "channels": 3,
                "dim_mults": [1, 2, 3, 4],
                "sparse_attn": "False",
                "attn_dim_head": 64,
                "attn_heads": 16,
                "self_attn": [false,true,true,true],
                "resnet_groups":[1,32,16,8]
        
	    }

Could I ask why this would happen? I found that this warning would affect my training  as it stopped after some steps and end up by NCCL error. Looking forward to your reply.

**Comment by rom1504** [comment]
isn't it the same as #188 ?

observed the same warning, no apparent consequences

**Comment by YUHANG-Ma** [comment]
> isn't it the same as #188 ?
> 
> observed the same warning, no apparent consequences

yes, the same. I have no idea how to fix this warning.

**Comment by rom1504** [comment]
@YUHANG-Ma could you make a PR please ?

**Comment by YUHANG-Ma** [comment]
> please

Could I ask what PR means?

**Comment by rom1504** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
