### ISSUE TITLE
🤔 

### ISSUE THREAD

**Issue by nousr** [lucidrains/DALLE2-pytorch#200]
https://github.com/lucidrains/DALLE2-pytorch/blob/a59882001267caef4ccf2879dc9b7efcccb6d93a/dalle2_pytorch/dalle2_pytorch.py#L1064-L1068

**Comment by lucidrains** [comment]
@nousr yes indeed! https://github.com/lucidrains/DALLE2-pytorch/commit/3dae43fa0ef2c5a29df9c275b1ebeb1a65c3bac5 :pray:
