### ISSUE TITLE
Code error (minor)

### ISSUE THREAD

**Issue by MalumaDev** [lucidrains/DALLE2-pytorch#206]
https://github.com/lucidrains/DALLE2-pytorch/blob/972ee973bc11d18ffe4e13f83a1a1a44f575f921/dalle2_pytorch/dalle2_pytorch.py#L1660

`ConvTransposeUpsample` is not declared! At this point `pixel_shuffle_upsample` parameter is useless!

**Comment by lucidrains** [comment]
@MalumaDev oops! thanks :) https://github.com/lucidrains/DALLE2-pytorch/commit/cc0f7a935c093714855564e362af0ac2b0d8b318
