### ISSUE TITLE
0 is a valid token (a note to potentially improve masking method?)

### ISSUE THREAD

**Issue by nousr** [lucidrains/DALLE2-pytorch#207]
![image](https://user-images.githubusercontent.com/51308183/178815193-7d039761-0518-481f-9290-27599d0908a5.png)

So, after yesterday I was reminded of some experiments I had done with kat a few months ago. 

Basically, the `0` token is `!` with no word boundary, There are a few common cases where this crops up I gave one common example above.

I believe the current method for masking looks at all `0` values and marks them, however, the ideal method would be to find the `0` tokens after the `<eos>` token and only mask those.

**Comment by lucidrains** [comment]
@nousr this should address it! https://github.com/lucidrains/DALLE2-pytorch/commit/f9882077188e9846ebf67bd78b2f8621754232ab
