### ISSUE TITLE
Optimal max_text_length & Memory Requirements

### ISSUE THREAD

**Issue by nousr** [lucidrains/DALLE2-pytorch#208]
Some quick questions regarding the latest update to the prior:
1. The prior network now has `max_text_length` as an option, however, it is my understanding that the `OpenAI ViT-L/14` clip model was trained only only `77` token sequences. If this is true (still waiting for some other people to confirm this)--would it be useless to set `max_text_length` to anything longer than `77`?
2. Will `max_text_length` affect the memory requirements of the model during training? After the updates I've had to reduce my batch size by 1/3

**Comment by lucidrains** [comment]
@nousr yup that's correct, you can just set it to 77 and save on memory!

**Comment by lucidrains** [comment]
i wasn't sure what the max text length was for CLIP

**Comment by lucidrains** [comment]
@nousr also, do you have Signal? you can always message me through there

send me an email and i can send you my number

**Comment by nousr** [comment]
thanks!
