### ISSUE TITLE
Minimal GPU requirements for training

### ISSUE THREAD

**Issue by chamecall** [lucidrains/DALLE2-pytorch#22]
Hello guys. Thanks for doing the amazing job first.
The question is what would be the minimal GPU requirements for training your implementation and are there any configurable arch blocks we could choose from to change a number of trained parameters if needed?
I have 3090 and wondering if it would be possible to use it for training.

**Comment by rom1504** [comment]
Looking at appendix C from dalle2 paper, the training requirement should be about 100k-200k GPUs hours so that's 256 v100 for 2-4 weeks.

Now is it possible to train small scale models with one GPU ? Quite possible, it was possible with dalle1. You'll have to try it out :)

**Comment by ariel415el** [comment]
Can you explain how you ended up with this number? I didn't find any such numbers in appendix C in the paper. Did you infer it from the time it takes to train GLIDE ?
