### ISSUE TITLE
Issue when trying to reproduce the scripts from the readme

### ISSUE THREAD

**Issue by ethancohen123** [lucidrains/DALLE2-pytorch#220]
Hi,
I tried to run the test script from the readme and I obtained this error:

AssertionError: text_embed_dim must be given to the unet if cond_on_text_encodings is True

Could you tell me whats wrong pls ?

**Comment by lucidrains** [comment]
@ethancohen123 oh sorry, can you try again with 1.2.1? https://github.com/lucidrains/DALLE2-pytorch/commit/36fb46a95e59a415cf0826fa569ed50c1c89f78c

**Comment by lucidrains** [comment]
@ethancohen123 doh, try again? https://github.com/lucidrains/DALLE2-pytorch/commit/80046334ad673c5833e5f1f325880ef95f29ac9b :pray:

**Comment by ethancohen123** [comment]
works just fine thanks !
