### ISSUE TITLE
Using home made clip

### ISSUE THREAD

**Issue by ethancohen123** [lucidrains/DALLE2-pytorch#223]
Hi,
Is there a way to use a different CLIP modules that is home made ? If yes, is there any guidelines for what it should return to work with dalle-2 ?

**Comment by lucidrains** [comment]
@ethancohen123 Hi Ethan

Yea it is possible, if you adhere to this interface https://github.com/lucidrains/DALLE2-pytorch/blob/main/dalle2_pytorch/dalle2_pytorch.py#L196

**Comment by RaSah673** [comment]
Hi,
Is the DALLE-2 Pytorch an open source project? Can I use it to develop for absolutely different text-to-image generation project? If yes, how can I remove pretreating images and add my own ones?

**Comment by lucidrains** [comment]
@RaSah673 yup, it is MIT licensed, which means you can do whatever you want with the codebase!

**Comment by RaSah673** [comment]
Thank you [lucidrains], but with "... you can do whatever you want with the codebase!" do you mean that there is also something else besides the codebase that is not open source?

**Comment by lucidrains** [comment]
not really, everything is open sourced

you can play around with a preliminary model [here](https://github.com/LAION-AI/dalle2-laion)
