### ISSUE TITLE
How to use the pre-trained model

### ISSUE THREAD

**Issue by zhenfan0753** [lucidrains/DALLE2-pytorch#229]
Hi, I'm trying to use pre-trained model to generate images. And I downloaded some models in [huggingface](https://huggingface.co/zenglishuci/conditioned-prior), then I use the cli tool.
```
dalle2_pytorch --model best.pth "a cat"
```
But it didn't show any result. 

If the cli tool does not ready to use , how can I load pre-trained models and generate some images? 
Please show me some code demo.

Please help, thx!

**Comment by Veldrovive** [comment]
For loading and using models trained by LAION, like the one you linked, it is much easier to use this [separate repo](https://github.com/LAION-AI/dalle2-laion) that was built for testing our models. In that repo you just need to run `python example_inference.py dream` and it will download the correct models and allow you to enter prompts.

If you wanted to use only this main repo, you would need to construct the state dict for the full model before trying to load it like this.
