### ISSUE TITLE
Potential bug: unused variable

### ISSUE THREAD

**Issue by xiankgx** [lucidrains/DALLE2-pytorch#237]
Hi, is there a typo somewhere in this function? The text_embeds is created but not used.

https://github.com/lucidrains/DALLE2-pytorch/blob/main/dalle2_pytorch/dalle2_pytorch.py#L1073-L1077

**Comment by lucidrains** [comment]
@xiankgx thanks for catching this! :pray:  https://github.com/lucidrains/DALLE2-pytorch/commit/8bbc956ff14852e6faf9bc21bba884c34630626f
