### ISSUE TITLE
DecoderTrainer    save() and load（）error  Seems to be a clip construction issue

### ISSUE THREAD

**Issue by FTKyaoyuan** [lucidrains/DALLE2-pytorch#244]
During training I use the following code to save
`decoder_trainer.save("best_u2_decoder.pth")`
train it then Use the code below to load
`decoder1 =DecoderTrainer.load("best_u2_decoder.pth")`

but An error occurred
![image](https://user-images.githubusercontent.com/59943491/191303637-5d126d58-14b7-4f34-ac84-a9ffad3b2df9.png)
![image](https://user-images.githubusercontent.com/59943491/191303880-96af6b19-207a-466e-9f1d-6a67ea1c179c.png)
I don't know what this means
maybe my parameters are wrong

**Comment by lucidrains** [comment]
@FTKyaoyuan you accidentally added a `d` after property on line 213
