### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by shnippi** [lucidrains/DALLE2-pytorch#25]
Hello everyone!

First of all, thank you so much for this cool repo and all the work that went into it. Im really interested in trying this out for myself, however with my current hardware it would take me half a year to train :). I was wondering if anyone would be able to share their pretrained weights with me. It would be greatly appreciated.

Have a nice day

**Comment by rom1504** [comment]
There is no such pretrained weights yet, but that's definitely something
I'm sure people will share when they exist.

You might want to check #23 where we're working on that. More contributors
is always useful

**Comment by Penghmed** [comment]
Is have any code for inference? No need training. Thanks.

**Comment by rom1504** [comment]
No
