### ISSUE TITLE
Missing positional embedding in ViT-VQGAN implementation 

### ISSUE THREAD

**Issue by usryokousha** [lucidrains/DALLE2-pytorch#252]
Hi Phil, it looks like no positional embedding was included in the encoder or decoder parts of ViT-based VQGAN model.  Was that intentional?

**Comment by lucidrains** [comment]
@usryokousha hey, the vit-vqgan here isn't well tested

but i've done a few training runs on https://github.com/lucidrains/parti-pytorch/blob/main/parti_pytorch/vit_vqgan.py and it works given sufficient number of patches. comes with a functional trainer too

**Comment by lucidrains** [comment]
@usryokousha to address your question, it does not need positional encoding, as the convolutions before the attention generates the positions

this is well studied https://arxiv.org/abs/2102.10882

**Comment by usryokousha** [comment]
Thanks for the kind reply!

I understand how position is implicit in convolutions, but I'm not following how a patch embedding leads to some positional bias in the transformer.  Are you referring to convolutions in place of FC layers? 

Yes, it looks like your implementation in [parti-pytorch](https://github.com/lucidrains/parti-pytorch/blob/main/parti_pytorch/vit_vqgan.py) included the relative positional encoding in the attention module.  BEiT2 also used the same positional encoding in their transformer-based dVAE.

**Comment by usryokousha** [comment]
@lucidrains I think for now I can close the issue since the code is there and essentially a tested version exists in parti-pytorch
