### ISSUE TITLE
How can I change Cuda to CPU in dalle2 on Mac?

### ISSUE THREAD

**Issue by iaa2005** [lucidrains/DALLE2-pytorch#26]
AssertionError: Torch not compiled with CUDA enabled

     87 # do above for many steps
     89 dalle2 = DALLE2(
     90     prior = diffusion_prior,
     91     decoder = decoder
     92 )
---> 94 images = dalle2(
     95     ['cute puppy chasing after a squirrel'],
     96     cond_scale = 2. # classifier free guidance strength (> 1 would strengthen the condition)
     97 )
     99 images

**Comment by iaa2005** [comment]
` 
     87 # do above for many steps
     89 dalle2 = DALLE2(
     90     prior = diffusion_prior,
     91     decoder = decoder
     92 )
---> 94 images = dalle2(
     95     ['cute puppy chasing after a squirrel'],
     96     cond_scale = 2. # classifier free guidance strength (> 1 would strengthen the condition)
     97 )
     99 images
`

**Comment by iaa2005** [comment]
And what about "# do above for many steps"? What should I do in my code for many steps? Which parts I need to repeat several times in code after "Let's see the whole script below ..( this code)"  in README?

**Comment by iaa2005** [comment]
?

**Comment by rom1504** [comment]
Hey @iaa2005 , what are you trying to build?

This repo currently contains only the model code.
You will need to write a training loop, get a dataset and use a high end GPU for training for a few days to get results.

There is no pretrained model to use yet.

**Comment by rom1504** [comment]
You may be interested by #23 and #27

**Comment by lucidrains** [comment]
> Ok, it works. I changed cuda in your code to cpu. And I have one question: how to convert images(type: tensor) to png image and save it in the directory?:
> 
> ```
> dalle2 = DALLE2(
>     prior = diffusion_prior,
>     decoder = decoder
> )
> 
> images = dalle2(
>     ['cute puppy chasing after a squirrel'],
>     cond_scale = 2. # classifier free guidance strength (> 1 would strengthen the condition)
> )
> 
> # save your image (in this example, of size 256x256)
> ```

i've addressed this in the latest version, you'll simply have to do `dalle([<prompt>], return_pil_images = True` to get it back as pillow images, which you can then just do a `.save('/path/to/<prompt>.png')`
