### ISSUE TITLE
Variable not defined in "noise=pred_noise".

### ISSUE THREAD

**Issue by Alexander-Jin** [lucidrains/DALLE2-pytorch#266]
My IDE (VS code) reports error on this line:

https://github.com/lucidrains/DALLE2-pytorch/blob/91c8d1ca1329644d75853fe8992d6aac03b2a992/dalle2_pytorch/dalle2_pytorch.py#L1323

I went over code base. It seems pred_noise is not defined. Maybe here it should be "noise = pred"? This is the first time I worked with this. Not sure if I understand it correctly.

**Comment by lucidrains** [comment]
@Alexander-Jin oops! thank you Alexander! (you won't use this setting anyways for diffusion prior haha)
