### ISSUE TITLE
Error while training DiffusionPrior

### ISSUE THREAD

**Issue by sr5434** [lucidrains/DALLE2-pytorch#278]
I am trying to train a DALL-E-2 diffusion prior, but I get the following error message: ```
RuntimeError                              Traceback (most recent call last)
[<ipython-input-57-2c767efa316d>](https://localhost:8080/#) in <module>
     13 )
     14 
---> 15 loss = diffusion_prior(text, images)
     16 loss.backward()

4 frames
[/usr/local/lib/python3.8/dist-packages/clip/model.py](https://localhost:8080/#) in encode_text(self, text)
    340         x = self.token_embedding(text).type(self.dtype)  # [batch_size, n_ctx, d_model]
    341 
--> 342         x = x + self.positional_embedding.type(self.dtype)
    343         x = x.permute(1, 0, 2)  # NLD -> LND
    344         x = self.transformer(x)

RuntimeError: The size of tensor a (13) must match the size of tensor b (77) at non-singleton dimension 1
```
I am using a Google Colab notebook and was unable to identify the problem. How do I fix it?

**Comment by lucidrains** [comment]
@sr5434 hey Samir, do you want to try the latest version and see if this resolves [your issue](https://github.com/lucidrains/DALLE2-pytorch/commit/cc58f75474b15ad857fe3baa38d1920b9c4275fa)

@rom1504 was gracious enough to update the depending package

**Comment by lucidrains** [comment]
@sr5434 just so you know though, the new SOTA is now [OpenClip](https://laion.ai/blog/large-openclip/)

highly recommend using their model instead!

**Comment by sr5434** [comment]
The bug still occurs, but with a slightly different error message:
```
RuntimeError                              Traceback (most recent call last)
[<ipython-input-21-2c767efa316d>](https://localhost:8080/#) in <module>
     13 )
     14 
---> 15 loss = diffusion_prior(text, images)
     16 loss.backward()

7 frames
[/usr/local/lib/python3.8/dist-packages/torchvision/transforms/functional_tensor.py](https://localhost:8080/#) in normalize(tensor, mean, std, inplace)
    938     if std.ndim == 1:
    939         std = std.view(-1, 1, 1)
--> 940     return tensor.sub_(mean).div_(std)
    941 
    942 

RuntimeError: The size of tensor a (30) must match the size of tensor b (3) at non-singleton dimension 0
```

**Comment by sr5434** [comment]
@lucidrains how do I fix the aforementioned issue?
