### ISSUE TITLE
Question about `one_unet_in_gpu`

### ISSUE THREAD

**Issue by FindHao** [lucidrains/DALLE2-pytorch#281]
Hi, we found many memory copies from [one_unet_in_gpu](https://github.com/lucidrains/DALLE2-pytorch/blob/main/dalle2_pytorch/dalle2_pytorch.py#L2724). In our tests, `self.unets.` locates at GPU and they are copied to CPU by  `self.unets.cpu()` . Then, only one unet will be copied to GPU by `unet.cuda()`. The last for loop will copy all back to where they were originally located. Since it is managed by `contextmanager`, only one `unet` locates at GPU during the context. 

Could you tell me the purpose of doing so? Why only one `unet` should be left on GPUs? Is it used to save GPU memory?

**Comment by FindHao** [comment]
From the [previous comment](https://github.com/lucidrains/DALLE2-pytorch/commit/27a33e1b2016ac384174054ba54719408f9883f5), looks like it is used to GPU memory efficiency. However, for GPUs having over 40GB of memory like A100, the memory copies take about 50% of the total execution time. So I think we need a smarter memory management here like check the GPU memory capacity or mode before do the offload.

**Comment by lucidrains** [comment]
@FindHao hey, so realistically you would only train one unet at a time, so moving all the other networks over to cpu, and the main network over to gpu, only happens once

is there a big issue with that?

**Comment by FindHao** [comment]
What do you mean `at a time`? You mean for each iteration inside the training?
In our tests, if we keep all unets on GPUs, the inference speedup is about 10X on A100 for one iteration.

**Comment by Veldrovive** [comment]
Yes, the idea is that you can train the first unet to decode from the embedding to a row res image for many epochs until you get a good result, then move on to training the upsamplers one at a time. I am not sure if there are full examples of that type of training.

**Comment by Veldrovive** [comment]
Ah, here's the one I was using for testing:
```json
{
    ...
    "decoder": {
        "unets": [
            {
                "dim": 32,
                ...
            },
            {
                "dim": 32,
                ...
            },
            {
                "dim": 192,
                ...
            }
        ],
        "clip": {
            "make": "openai",
            "model": "ViT-L/14"
        },
        "image_sizes": [64, 256, 1024],
        "random_crop_sizes": [null, null, 256],
        "channels": 3,
        "timesteps": 1000,
        "loss_type": "l2",
        "beta_schedule": ["cosine", "cosine", "cosine"],
        "learned_variance": true,
        "text_cond_drop_prob": 0.0,
        "image_cond_drop_prob": 0.0
    },
    ...
    "train": {
        "epochs": 1000,
        "lr": 1.2e-4,
        "wd": 0.0,
        "max_grad_norm": 0.5,
        "save_every_n_samples": 2000000,
        "n_sample_images": 2,
        "device": "cuda:0",
        "epoch_samples": 10000000,
        "validation_samples": 100000,
        "use_ema": true,
        "ema_beta": 0.9999,
        "unet_training_mask": [false, false, true]
    },
    ...
}
```
So this would only train the third unet and would avoid the memory issues.

**Comment by FindHao** [comment]
@Veldrovive So, you mean it is possible that this function could be executed multiple times during the whole training, right? I'm not familiar with dalle2. Could you tell me why your example config only trains the third unet and avoid memory issues?

**Comment by Veldrovive** [comment]
This is a config file used to initialize training of the third unet. In general, when training a model from scratch, you would first define the `decoder` section of the config where you set all the parameters for the unets and this section would not change throughout the training process. In this case we are defining a full decoder consisting of 3 unets that decode to 64x64 first, the upsamples to 256 and finally 1024.

The training section would change based on which unet you are training at the time. To avoid the memory transfer issues, `unet_training_mask` should only have one value set to `true`. For a full example of a config, you can look [here](https://github.com/lucidrains/DALLE2-pytorch/tree/main/configs).

**Comment by FindHao** [comment]
@Veldrovive Thanks for your clarification!  But for the configurations using all unets, the issue still exists, right?

In your config, even you only use one unet, there are still memory copies for this unet, right? [self.unets.cpu()](https://github.com/lucidrains/DALLE2-pytorch/blob/main/dalle2_pytorch/dalle2_pytorch.py#L2733) copies all unets(only one) to CPU, then the following `unet.cuda()` will copy it back to GPU, right?

**Comment by FindHao** [comment]
The calling context is like [one_unet_in_gpu](https://github.com/lucidrains/DALLE2-pytorch/blob/main/dalle2_pytorch/dalle2_pytorch.py#L2724) -->(is called by) [sample](https://github.com/lucidrains/DALLE2-pytorch/blob/main/dalle2_pytorch/dalle2_pytorch.py#L3149) --> [forward](https://github.com/lucidrains/DALLE2-pytorch/blob/main/dalle2_pytorch/dalle2_pytorch.py#L3307). So it looks like each forward layer will do such memory copies.

**Comment by lucidrains** [comment]
@FindHao ahh yes, that is true

do you want to try the latest version and see if it is any more performant?

i've also added [a way](https://github.com/lucidrains/DALLE2-pytorch/commit/580274be79c4cb11e1fe1ef9dcaaeba9c7be669a#diff-038ecede954c29266888cb88e37cc06f61ba2433f8b5142c7b2b2cefde5ed0edR3123) to disable it

**Comment by lucidrains** [comment]
@Veldrovive  also, hi :wave: hope all is well

**Comment by FindHao** [comment]
@lucidrains 
I use the version in our [TorchBench](https://github.com/pytorch/benchmark/tree/main/torchbenchmark/models/DALLE2_pytorch). I manually update the DALLE2_pytorch by `pip install -U`, but looks like the latest version(1.12.4) can't stop its execution. It maybe because our configurations.

I don't think [change it to `to`](https://github.com/lucidrains/DALLE2-pytorch/commit/580274be79c4cb11e1fe1ef9dcaaeba9c7be669a#diff-038ecede954c29266888cb88e37cc06f61ba2433f8b5142c7b2b2cefde5ed0edR2738) would solve the issue since you still copy all modules to CPU, one back to GPU, and all other back to GPU again. 

I think a better solution could be like the following:
1. Check the GPU memory capacity, if it is larger than 40GB(or a better number?), just ignore `one_unet_in_gpu` and context. 
2. If have to do so, at least we can ignore the specified unet's copies. 

Definitely manually disabling it by setting `one_unet_in_gpu_at_time` to false could be a solution but it relies on users' experience.

**Comment by lucidrains** [comment]
@FindHao i think for now perhaps best to just let users use this flag, as determining whether all the unets can fit in memory depends on a couple factors

**Comment by lucidrains** [comment]
@FindHao does that flag solve your original issue?

**Comment by FindHao** [comment]
> @FindHao does that flag solve your original issue?

Yes, it works. Thanks for your update!

I also manually modify the version TorchBench used with `.to`. The execution time is still 10X slower than no copies.

**Comment by lucidrains** [comment]
@FindHao ok! you can just use the benchmark with that flag turned off then! thanks
