### ISSUE TITLE
Field required in train_decoder_example config

### ISSUE THREAD

**Issue by u1ug** [lucidrains/DALLE2-pytorch#307]
Receiving pydantic errors when attempting to train decoder with example config:
`Field required [type=missing, input_value={'dim': 128, 'image_embed...': 32, 'attn_heads': 16}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing
decoder.unets.``tuple[...]``.0.self_attn
  Field required [type=missing, input_value={'dim': 128, 'image_embed...': 32, 'attn_heads': 16}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing
decoder.clip
  Field required [type=missing, input_value={'unets': [{'dim': 128, '...learned_variance': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing
train.epoch_samples
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.4/v/int_type
train.validation_samples
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.4/v/int_type`

**Comment by 1390806607** [comment]
Hello, I have the same problem. Have you solved it

**Comment by lucidrains** [comment]
@1390806607 could you retry with 1.15.3?

**Comment by 1390806607** [comment]
thank you

**Comment by 1390806607** [comment]
The code I used is 1.15.3

**Comment by lucidrains** [comment]
@1390806607 could you paste your error?

**Comment by 1390806607** [comment]
![image](https://github.com/lucidrains/DALLE2-pytorch/assets/89060957/9e182fca-0c62-4bee-b2fc-8c95b37b84d4)

**Comment by lucidrains** [comment]
@1390806607 try 1.15.5?

**Comment by 1390806607** [comment]
Let me try. Is there a big difference between the two versions of code

**Comment by 1390806607** [comment]
{
    "decoder": {
        "unets": [
            {
                "dim": 128,
                "image_embed_dim": 768,
                "cond_dim": 64,
                "channels": 3,
                "dim_mults": [1, 2, 4, 8],
                "attn_dim_head": 32,
                "attn_heads": 16
            }
        ],
        "image_sizes": [64],
        "channels": 3,
        "timesteps": 1000,
        "loss_type": "l2",
        "beta_schedule": ["cosine"],
        "learned_variance": true
    },
    "data": {
        "webdataset_base_url": "E:/company_wy/DALLE2-pytorch-1.15.5/mscoco/00000.tar",
        "img_embeddings_url": "E:/company_wy/DALLE2-pytorch-1.15.5/embeddings/img_emb",
        "num_workers": 4,
        "batch_size": 64,
        "start_shard": 0,
        "end_shard": 9999999,
        "shard_width": 6,
        "index_width": 4,
        "splits": {
            "train": 0.75,
            "val": 0.15,
            "test": 0.1
        },
        "shuffle_train": true,
        "resample_train": false,
        "preprocessing": {
            "RandomResizedCrop": {
                "size": [128, 128],
                "scale": [0.75, 1.0],
                "ratio": [1.0, 1.0]
            },
            "ToTensor": true
        }
    },
    "train": {
        "epochs": 20,
        "lr": 1e-4,
        "wd": 0.01,
        "max_grad_norm": 0.5,
        "save_every_n_samples": 100000,
        "n_sample_images": 6,
        "device": "cuda:0",
        "epoch_samples": null,
        "validation_samples": null,
        "use_ema": true,
        "ema_beta": 0.99,
        "amp": false,
        "unet_training_mask": [true]
    },
    "evaluate": {
        "n_evaluation_samples": 1000,
        "FID": {
            "feature": 64
        },
        "IS": {
            "feature": 64,
            "splits": 10
        },
        "KID": {
            "feature": 64,
            "subset_size": 10
        },
        "LPIPS": {
            "net_type": "vgg",
            "reduction": "mean"
        }
    },
    "tracker": {
        "overwrite_data_path": true,

        "log": {
            "log_type": "wandb",

            "wandb_entity": "c9117a62c11b6824fa20ef073761b14d2aa814b9",
            "wandb_project": "decoder_train",

            "verbose": true
        },

        "load": {
            "load_from": null
        },

        "save": [{
            "save_to": "wandb",
            "save_latest_to": "latest.pth"
        }, {


            "save_latest_to": "./decoder_model/latest.pth",
            "save_best_to": "./decoder_model/best.pth",
            "save_meta_to": "./decoder_model/assorted/files",

            "save_type": "model"
        }]
    }
}

My parameter


python train_decoder.py   errors

{'decoder': {'unets': [{'dim': 128, 'image_embed_dim': 768, 'cond_dim': 64, 'channels': 3, 'dim_mults': [1, 2, 4, 8], 'attn_dim_head': 32, 'attn_heads': 16}], 'image_sizes': [64], 'channels': 3, 'timesteps': 1000, 'loss_type': 'l2', 'beta_schedule': ['cosine'], 'learned_variance': True}, 'data': {'webdataset_base_url': 'E:/company_wy/DALLE2-pytorch-1.15.5/mscoco/00000.tar', 'img_embeddings_url': 'E:/company_wy/DALLE2-pytorch-1.15.5/embeddings/img_emb', 'num_workers': 4, 'batch_size': 64, 'start_shard': 0, 'end_shard': 9999999, 'shard_width': 6, 'index_width': 4, 'splits': {'train': 0.75, 'val': 0.15, 'test': 0.1}, 'shuffle_train': True, 'resample_train': False, 'preprocessing': {'RandomResizedCrop': {'size': [128, 128], 'scale': [0.75, 1.0], 'ratio': [1.0, 1.0]}, 'ToTensor': True}}, 'train': {'epochs': 20, 'lr': 0.0001, 'wd': 0.01, 'max_grad_norm': 0.5, 'save_every_n_samples': 100000, 'n_sample_images': 6, 'device': 'cuda:0', 'epoch_samples': None, 'validation_samples': None, 'use_ema': True, 'ema_beta': 0.99, 'amp': False, 'unet_training_mask': [True]}, 'evaluate': {'n_evaluation_samples': 1000, 'FID': {'feature': 64}, 'IS': {'feature': 64, 'splits': 10}, 'KID': {'feature': 64, 'subset_size': 10}, 'LPIPS': {'net_type': 'vgg', 'reduction': 'mean'}}, 'tracker': {'overwrite_data_path': True, 'log': {'log_type': 'wandb', 'wandb_entity': 'c9117a62c11b6824fa20ef073761b14d2aa814b9', 'wandb_project': 'decoder_train', 'verbose': True}, 'load': {'load_from': None}, 'save': [{'save_to': 'wandb', 'save_latest_to': 'latest.pth'}, {'save_latest_to': './decoder_model/latest.pth', 'save_best_to': './decoder_model/best.pth', 'save_meta_to': './decoder_model/assorted/files', 'save_type': 'model'}]}}
Traceback (most recent call last):
  File "E:\company_wy\DALLE2-pytorch-1.15.5\train_decoder.py", line 651, in <module>
    main()
  File "E:\anaconda\envs\dalle\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "E:\anaconda\envs\dalle\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "E:\anaconda\envs\dalle\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\anaconda\envs\dalle\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "E:\company_wy\DALLE2-pytorch-1.15.5\train_decoder.py", line 647, in main
    config = TrainDecoderConfig.from_json_path(str(config_file_path))
  File "E:\company_wy\DALLE2-pytorch-1.15.5\dalle2_pytorch\train_configs.py", line 351, in from_json_path
    return cls(**config)
  File "E:\anaconda\envs\dalle\lib\site-packages\pydantic\main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for TrainDecoderConfig
decoder.unets.list[UnetConfig].0.self_attn
  Field required [type=missing, input_value={'dim': 128, 'image_embed...': 32, 'attn_heads': 16}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing
decoder.unets.`tuple[...]`.0.self_attn
  Field required [type=missing, input_value={'dim': 128, 'image_embed...': 32, 'attn_heads': 16}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing

Process finished with exit code 1
@lucidrains Hello, can you take a look for me

**Comment by 1390806607** [comment]
I added "self_attn" to unet in train_decoder_config.example.json :[false,true,true,true] The above problem was solved, but I ran into a new problem, It's a little long in generating example data.

![image](https://github.com/lucidrains/DALLE2-pytorch/assets/89060957/35b16c95-c8d7-4df2-adc0-6fd6098f004b)
@lucidrains

**Comment by lucidrains** [comment]
@1390806607  1.15.6?

**Comment by lucidrains** [comment]
@1390806607 ah, make [this change](https://github.com/lucidrains/DALLE2-pytorch/commit/b6fecae91a22b7b969a3991f56b6771d36082486#diff-1960fa4032117c7620576aea3bf67f017dd87a2077278af4c2f17abf549114b0R639), or update to latest with a git pull

**Comment by 1390806607** [comment]
1.15.5, 1.15.6 I'll try it

**Comment by 1390806607** [comment]
@lucidrains   Is this normal
![image](https://github.com/lucidrains/DALLE2-pytorch/assets/89060957/542f7d49-2d8e-48f4-a388-8f1f414929fa)

**Comment by lucidrains** [comment]
@1390806607 nope, not normal

try updating yet again

**Comment by 1390806607** [comment]
@lucidrains     I'll pull it up using git pull,        I still look like this after running again. How can I solve this problem                      
![image](https://github.com/lucidrains/DALLE2-pytorch/assets/89060957/4be16d29-7cfe-479e-b1e6-a2f32f1eb9b8)
