### ISSUE TITLE
LowResCond downsample bug

### ISSUE THREAD

**Issue by xiankgx** [lucidrains/DALLE2-pytorch#32]
I think you tried to resize to downsample_image_size but instead resize to target_image_size.

https://github.com/lucidrains/DALLE2-pytorch/blob/main/dalle2_pytorch/dalle2_pytorch.py#L1216

**Comment by lucidrains** [comment]
@xiankgx thank you for the code review! https://github.com/lucidrains/DALLE2-pytorch/commit/fb662a62f35a545632289c4013a97fa06c17af11
