### ISSUE TITLE
Q: Is there any specifications on the image pixel values for the decoder?

### ISSUE THREAD

**Issue by xiankgx** [lucidrains/DALLE2-pytorch#33]
Hi, do you know if there are any strict restrictions on the image input to the decoder? I remember it is mentioned to be [-1, +1] somewhere, but can we also used other values like [0, 1]? However, since we are adding random normal noise with mean 0 I guess not?

**Comment by lucidrains** [comment]
@xiankgx yea, this repository does it from -1 to +1, but i've seen some generative models out there (back when i trained a lot of GANs) that does it from 0 to 1. i don't actually know if i've ever read any papers that did a proper comparison between the two

**Comment by xiankgx** [comment]
We should be very careful when passing images to various places, for different CLIP implementations which expect different things, also as the prediction target or x_start for the decoder.

**Comment by lucidrains** [comment]
@xiankgx yes! we definitely need to keep an eye on normalization

**Comment by lucidrains** [comment]
@rom1504 yea, i think the issue is that the decoder will be trained images that are simply normalized to -1 to 1, but CLIP uses https://github.com/openai/CLIP/blob/main/clip/clip.py#L85 (but we can always just do this within the `embed_image` forward function for the CLIP adapter)

**Comment by rom1504** [comment]
I don't understand.
Doesn't the decoder take as input (image, clip embedding) ?
If yes, then how is the normalization used in the clip forward related with the decoder training process?

**Comment by lucidrains** [comment]
@rom1504 

basically, images usually start off normalized from a range of 0 to 1 (shrunk from 0 to 255)

for DDPMs, we normalize them to -1 to 1 using `2 * image - 1`

for CLIP, if we do all the embedding processing externally, then there is no problem - however, for the decoder, we currently take in the image and do both DDPM and derive the CLIP image embedding. so I just have to make sure to unnormalize the image before renormalizing it with what CLIP was trained on, before passing it into the attention net. you can double check my work here! https://github.com/lucidrains/DALLE2-pytorch/blob/main/dalle2_pytorch/dalle2_pytorch.py#L228

**Comment by rom1504** [comment]
ah I see, makes sense
