### ISSUE TITLE
Typo in VQ-VAE

### ISSUE THREAD

**Issue by CiaoHe** [lucidrains/DALLE2-pytorch#45]
Hi Phil,
great to see your big contributions. 
Here I find might be a typo. I thought it should be like `last_dec_layer = self.enc_dec.decoders[-1].weight`
https://github.com/lucidrains/DALLE2-pytorch/blob/c1db2753f5a425220f808da87d3fe208e97cf285/dalle2_pytorch/vqgan_vae.py#L846

Besides, in order to match the name with `ResEncDec` and `ConvNextEncDec`, I think it's better to rename `ViTEncDec`'s encoder and decoder as `self.encoders` and `self.decoders`

Enjoy!

**Comment by lucidrains** [comment]
@CiaoHe oh hey, long time! thanks for the code review (as usual :laughing:) and let me know if https://github.com/lucidrains/DALLE2-pytorch/releases/tag/0.0.89 fixes things

**Comment by CiaoHe** [comment]
great! It should be no problem. 
Recently I just follow stuffs related to diffusion model and other generation tracks. Hope to participate more on this replicationԅ(¯ㅂ¯ԅ)

**Comment by lucidrains** [comment]
> great! It should be no problem. Recently I just follow stuffs related to diffusion model and other generation tracks. Hope to participate more on this replicationԅ(¯ㅂ¯ԅ)

come on aboard! :D
