### ISSUE TITLE
Q: Why causal transformer in diffusion prior?

### ISSUE THREAD

**Issue by xiankgx** [lucidrains/DALLE2-pytorch#46]
I know we can but i don't understand why is the paper using causal transformer since we are not doing sequence predictions where what we are trying to predict is in the context. Here we are trying to predict the image embeddings which is not part of the context anywhere. What is the causal mask for? Please enlighten me.

**Comment by lucidrains** [comment]
my other guess is that they started off with the autoregressive prior, and somebody on the team (probably Nichol) proposed to turn it into a denoising network to overcome a few issues, so it was just a natural iteration on design
