### ISSUE TITLE
Show images

### ISSUE THREAD

**Issue by rizkidewanto** [lucidrains/DALLE2-pytorch#48]
How to show images after training?

**Comment by xiankgx** [comment]
Use the decoder sample method.

**Comment by laxmimerit** [comment]
How to show images? I am getting printed only noise? I ran the example shown in the readme.
```
import torchvision
imgs = images.cpu()
plt.imshow(torchvision.utils.make_grid(imgs, nrow=1).permute(1, 2, 0))
```
![image](https://user-images.githubusercontent.com/16714612/172439011-61b9e5a8-2fae-4eac-9cca-e8d4936481dd.png)
