### ISSUE TITLE
Fix bug in the eval function of the prior

### ISSUE THREAD

**Issue by rom1504** [lucidrains/DALLE2-pytorch#49]
https://github.com/lucidrains/DALLE2-pytorch/blob/main/train_diffusion_prior.py#L17 this function should compute a single averaged number and report it for the current training step
the current behavior is very confusing and wrong

**Comment by lucidrains** [comment]
@rom1504 oh oops, missed this in the review, should be good now, i think

**Comment by rom1504** [comment]
thanks
