### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by ltz0120** [lucidrains/DALLE2-pytorch#5]
Thank you for sharing the code. Could you please also share a pretrained model? Thank you! The model requires a lot of resources and is really hard to train.

**Comment by lucidrains** [comment]
the code isn't even done yet. i have no idea why the repository has this many stars tbh

**Comment by lucidrains** [comment]
i've linked to a discord in the readme. please check them out if you are interested in the eventual replicated model
