### ISSUE TITLE
Fix spikes in prior training

### ISSUE THREAD

**Issue by rom1504** [lucidrains/DALLE2-pytorch#50]
https://wandb.ai/laion/diffusion-prior/runs/3o0ic6ou?workspace=user-krish240574

![Screenshot_20220502_172341](https://user-images.githubusercontent.com/2346494/166260618-4f97fb00-21eb-46b9-b6a8-0a09f130ae11.png)

I figure it might be better after gradient cliping
can you rerun with the latest commits @krish240574  ?

**Comment by rom1504** [comment]
still happening after gradient cliping actually, but apparently it doesn't impact perf so maybe it's ok

**Comment by lucidrains** [comment]
@rom1504 added an option that may or may not help https://github.com/lucidrains/DALLE2-pytorch/blob/main/train_diffusion_prior.py#L185

**Comment by lucidrains** [comment]
@rom1504 added a few more stability measure, including two layernorms from the normformer paper, corroborated by @borisdayma 's experiments https://twitter.com/borisdayma/status/1517227191477571585
