### ISSUE TITLE
I just getting a noise

### ISSUE THREAD

**Issue by mfbulut** [lucidrains/DALLE2-pytorch#54]
Firstly I'm not a python programmer or intrested in ai I just want to make funny pictures I ran the script below text
"Let's see the whole script below" in README but I dont' know how to display tensor images so I googled it I wrote

`import matplotlib.pyplot as plt`
`iplt.imshow(  images[0].permute(1, 2, 0)  )`

then I got this 

![b33ec5fc-8b58-424c-89db-fa9c50f05fa8](https://user-images.githubusercontent.com/51883559/166484527-6aa8c206-3220-452d-bc14-a6915c932bac.png)

probably I made a dumb mistake somewhere pls help me

**Comment by xiankgx** [comment]
You are not wrong in doing that. Probably just need to inverse normalize values from minus to plus 1 to from 0 to 1.

**Comment by xiankgx** [comment]
You are getting just noise because you have not train the model.
