### ISSUE TITLE
Add doc for the prior training

### ISSUE THREAD

**Issue by rom1504** [lucidrains/DALLE2-pytorch#58]
hey @krish240574 , great training script for the prior!

it could be nice if you could add a few lines in a new section in the readme to explain how to run it (the command line along with a few explanations about the main parameters, and maybe one example wandb run), so everyone can run it

**Comment by krish240574** [comment]
Ok, I'll do that , gladly !

**Comment by krish240574** [comment]
Done, PR submitted. Please do take a look and comment.

**Comment by rom1504** [comment]
Great
