### ISSUE TITLE
Noise Output Result Issue

### ISSUE THREAD

**Issue by goldiusleonard** [lucidrains/DALLE2-pytorch#61]
@lucidrains 
I have the same issue with #54 . I have copied the training method in the readme, but I still got the noise output result. Can you see my code and check what is wrong with it?

https://github.com/goldiusleonard/Dalle2_pytorch_project

**Comment by lucidrains** [comment]
@goldiusleonard yea, so the training loop is actually more involved, but i hope to automate that all away in a CLI tool, by end of the month. it'll end up exactly like https://github.com/lucidrains/lightweight-gan  no-nonsense

**Comment by goldiusleonard** [comment]
> @goldiusleonard yea, so the training loop is actually more involved, but i hope to automate that all away in a CLI tool, by end of the month. it'll end up exactly like https://github.com/lucidrains/lightweight-gan no-nonsense

so any solution for my issue? Or I just need to train it in more epochs?

**Comment by lucidrains** [comment]
@goldiusleonard once you see the `(wip)` tag removed from the Training section, then it is ready for you

right now it is only accessible to deep learning practitioners

**Comment by lucidrains** [comment]
@goldiusleonard if you wish to collaborate with people who work with artificial intelligence, try joining the discord and be a fly on the wall. you'll learn lots
