### ISSUE TITLE
Unexpected keyword argument - l2_norm_output

### ISSUE THREAD

**Issue by krish240574** [lucidrains/DALLE2-pytorch#64]
/DALLE2-pytorch-main/dalle2_pytorch/dalle2_pytorch.py", line 660, in __init__
    self.causal_transformer = CausalTransformer(dim = dim, **kwargs)

TypeError: __init__() got an unexpected keyword argument 'l2norm_output'

I've pulled the latest code from this repo - did some fix break the code?

**Comment by lucidrains** [comment]
@krish240574 oh my bad! that has been removed when accounting for Katherine's suggestion about scaling the image embed. fixed in the latest! https://github.com/lucidrains/DALLE2-pytorch/commit/63029f7388a0b95e632181a274f8d99c2245ce4c

**Comment by krish240574** [comment]
@lucidrains thank you !
