### ISSUE TITLE
No run for GeForce 840M

### ISSUE THREAD

**Issue by nvaranki** [lucidrains/DALLE2-pytorch#69]
It looks like CUDA for GeForce 840M has not been recognized. Scripts failed.
```
# torch/cuda/__init__.py
hasattr(torch._C, '_cuda_getDeviceCount')  # is False
torch._C._cuda_setDevice(device)  # no such method
```

**Comment by nvaranki** [comment]
Windows 10
NVIDIA CUDA 11.5.76 driver
cuda_9.2.148_win10 was installed very long ago
there are other PyTorch scripts confirmed running cuda

**Comment by xiankgx** [comment]
Try update the drivers, CUDA, and reinstall Pytorch using commands suggested from Pytorch Get Started page.

**Comment by nvaranki** [comment]
"OpenAI's API is not available in your country." People, you really got crazy. Bye
