### ISSUE TITLE
Feature Request: Pytorch Lightning

### ISSUE THREAD

**Issue by egeozsoy** [lucidrains/DALLE2-pytorch#88]
I think it would be really beneficial to convert the DecoderTrainer and DiffusionModelTrainer to Pytorch Lightning if possible. First of all, it would be then trivial to support half-precision training, multi-gpu training, TPUS etc. Secondly it would reduce the code complexity significantly. What do you think @lucidrains

**Comment by lucidrains** [comment]
@egeozsoy i disagree with this, as i've had a bad experience trying to use them for GAN training (albeit GANs are a bit more difficult to setup) i'll think about it, but the only framework i'll consider atm would be DeepSpeed, given it has been proven out by Gpt-NeoX over at Eleuther.ai

**Comment by Borda** [comment]
> as i've had a bad experience trying to use them for GAN training (albeit GANs are a bit more difficult to setup)

may I kindly ask what versions you used? and what did you find as a bad user/dev experience?
