### ISSUE TITLE
Hardware requirements 

### ISSUE THREAD

**Issue by INF800** [lucidrains/DALLE2-pytorch#9]
Hi,

Let's say if the project completes -- what will be the hardware specs required to run the model?

Best,
Rakesh

**Comment by lucidrains** [comment]
@INF800 reportedly the model is smaller than DALL-E v1, so whatever the requirements of [ruDALLE](https://github.com/ai-forever/ru-dalle) is, but less

**Comment by INF800** [comment]
> @INF800 👋 reportedly the model is smaller than DALL-E v1, so whatever the requirements of [ruDALLE](https://github.com/ai-forever/ru-dalle) is, but less

Hi @lucidrains, how did you come to know DALLE2 is smaller than DALLE1? Would you kindly provide reference links? I tried to read paper but couldn't find any such information.

**Comment by johnpaulbin** [comment]
> > @INF800 👋 reportedly the model is smaller than DALL-E v1, so whatever the requirements of [ruDALLE](https://github.com/ai-forever/ru-dalle) is, but less
> 
> Hi @lucidrains, how did you come to know DALLE2 is smaller than DALLE1? Would you kindly provide reference links? I tried to read paper but couldn't find any such information.

I believe this is relevant:

The Dall-E 2 paper shows that the "base" model (64) is 3.5 Billion parameters in size.

![image](https://user-images.githubusercontent.com/43943237/163756669-9191e202-60db-4306-aeb3-bd835ea2f813.png)

This is from the Dall-E 1 paper:

![image](https://user-images.githubusercontent.com/43943237/163757001-d13ccfb8-f5cd-4a98-a5c1-a7c0c157a892.png)

**Comment by johnpaulbin** [comment]
So, theoretically, it is possible to run on free colab GPUs (K80 +)
Training should be possible with a T4 GPU

**Comment by INF800** [comment]
> So, theoretically, it is possible to run on free colab GPUs (K80 +) Training should be possible with a T4 GPU

Thankyou for this @johnpaulbin

**Comment by Nikuson123** [comment]
That's what I need, just can I use it in other models and how will it be limited by the license?
